### ISSUE TITLE
showTopic action lists old, cached page after creating a new post

### ISSUE THREAD

**Issue by BenjaminBeck** [jweiland-net/pforum#15]
I think it should delete the page cache for pidOfDetailPage

**Comment by sfroemkenjw** [comment]
Hello @BenjaminBeck 

that is default behavior of every extbase plugin. It is up to the integrator to set correct cache clearing:

https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/Extbase/Reference/Caching.html

And yes, there are solutions outside like done in news and events2 where the developers create and clear various cache tags automatically, but that is not a default for every extension.

Stefan
